### ISSUE TITLE
avoid doing these for paths

### ISSUE THREAD

**Issue by matcool** [abb2k/Backup#1]
https://github.com/abb2k/Backup/blob/85484e5fd9653f7d5177044699d715fb275b429e/src/main.cpp#L33-L44
this mod might be intentionally windows only but this code forces it to be windows only. please use the features of filesystem::path
```cpp
std::string fileName = "\\Backups"; 
 std::filesystem::create_directory(Mod::get()->getSaveDir().string() + fileName); 
```
into
```cpp
 std::filesystem::create_directory(Mod::get()->getSaveDir() / "Backups"); 
```

**Comment by matcool** [comment]
actually i just realized you use **std**::filesystem::path, so this wouldnt work on macos because of that too

**Comment by abb2k** [comment]
alr so i tried to do what you said and do you think this is better?
```
            geode::Result<> res = geode::utils::file::createDirectory(Mod::get()->getSaveDir() / "Backups");
            res = geode::utils::file::createDirectory(Mod::get()->getSaveDir() / "Backups/Auto-Backups");

            std::string pathToAutosaves = Mod::get()->getSaveDir().string() + "/Backups/Auto-Backups";

            auto creationTime = std::chrono::system_clock::to_time_t(std::chrono::system_clock::now());
            const char *Time = std::ctime(&creationTime);
            std::string t = Time;
            std::string fileName = "/Backups/Auto-Backups/--AutoBackup-- " + t;
            for (size_t i = 0; i < fileName.length(); i++)
```
also you said this wouldn't work on macos why is that and how can i make it work for it too?

**Comment by matcool** [comment]
this looks fine for macos, though another issue is converting the path to a string. avoid doing that if possible, as that'll break on unicode paths
